[[main]]
  name = "About"
  pageRef = "about"
  weight = 1

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 2

[[main]]
  name = "Playlist"
  pageRef = "fooo"
  weight = 3
  
[[main]]
  name = "练习故事"
  pageRef = "chinese"
  weight = 4

[[main]]
  identifier = "search"
  weight = 5
  [main.params]
    action = "search"
    icon = "search"
    